name: Publish Container image

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Container image to Quay
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME}}
          password: ${{ secrets.QUAY_TOKEN }}
      
      - name: Build and push Container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: quay.io/mk-ci-cd/consoledot-e2e:latest
